### ISSUE TITLE
Kleinskalierte Anzeige

### ISSUE THREAD

**Issue by ewertmaster** [rg-engineering/ioBroker.vis-weather#12]
Nach einem Daten-Update oder zwischendurch wird das Widget kleinskaliert. Nach einiger Zeit wechselt das Widget wieder zu der normalen Größe. Siehe Bild
<img width="613" alt="bildschirmfoto 2018-08-26 um 00 46 13" src="https://user-images.githubusercontent.com/42463785/44623257-0ecd5d00-a8ca-11e8-98ba-dc08cf672ad3.png">

**Comment by GermanBluefox** [comment]
Need a debug in developer mode.
Browser? Os?

**Comment by rg-engineering** [comment]
@ewertmaster do you have a log showing that behavior?

**Comment by ewertmaster** [comment]
I will try to create it this weekend. But actually i have no idea how to create a debug log in developer mode.

**Comment by rg-engineering** [comment]
do you still run vis in safari? What is your operating system?

**Comment by ewertmaster** [comment]
For the VIS, I use the Chrome browser. This runs on a Raspberry Pi in Kios Mode.
But the same Issue i see in Safari, Opera and Firefox running on OSX.

**Comment by ewertmaster** [comment]
<img width="776" alt="bildschirmfoto 2018-09-28 um 12 49 57" src="https://user-images.githubusercontent.com/42463785/46204345-37a79e80-c31d-11e8-9120-9b8b159bbb11.png">
With Firefox I get the following error message in the browser log

**Comment by oke24** [comment]
Vielen Dank für das Update auf 2.2.x. Leider funktioniert Weatherunderground nicht mehr mit dieser Version.  Weatherunderground als Quelle wird nicht mehr erkannt, und somit die Datenstrukturen nicht eingelesen. 

![vis-weather-2 2 1](https://user-images.githubusercontent.com/46261409/50547294-a7d50180-0c37-11e9-82ae-472f51f519c4.png)
![vis-weather-2 1 0](https://user-images.githubusercontent.com/46261409/50547304-ba4f3b00-0c37-11e9-9c3b-1efc28e59336.png)

**Comment by rg-engineering** [comment]
Das Umschalten für die Datenstruktur (NextDaysDetailed, NextHours, usw) funktioniert nur bei DasWetter. Bei Umschalten auf WU lösche ich die Auswahl und das sollte keine Auswirkung haben. Evtl. einfach noch mal die Instanz ändern (z.Bsp. die .0 löschen und wieder eingeben). Wenn das nicht hilft, brauche ich das log aus der browser - Konsole... Danke für die Hilfe!

**Comment by oke24** [comment]
Vielen Dank für die schnelle Antwort. Bei mir wird beim Hereinziehen des weather-Widgets in den VIS-Editor die Datenstruktur von Das Wetter bereits vorbelegt, auch ohne Angabe einer Wetterinstanz. 
Das ändert sich auch nicht, wenn man die Instanz füllt oder ändert, z.B. wie bei mir in weatherunderground.0. Es bleibt weiterhin die Datenstruktur von Das Wetter vorbelegt. Es müsste jetzt ja ein Umschalten von "Datenstruktur" auf "Zeitintervall" stattfinden. 
Anbei das Browser-Consolen-Log.
[vis-weather-2.2.1.zip](https://github.com/rg-engineering/ioBroker.vis-weather/files/2717212/vis-weather-2.2.1.zip)



![vis-weather-2 2 1 -1](https://user-images.githubusercontent.com/46261409/50547947-875f7400-0c44-11e9-8f41-e530e58eb872.png)

**Comment by rg-engineering** [comment]
ja, genau. sobald man "weatherunderground.0" als Instanz eingibt, sollte der Eintrag unter "Datenstruktur" gelöscht werden. Leider deckt das log genau das nicht ab. Ich würde einen Eintrag der Art
```
--------- : w00630 - wetter - weatherunderground.0 - instance
instance changed to weatherunderground.0 old structure = 
```
erwarten. Das finde ich in dem log aber leider nicht, aber genau da würde ich den Fehler erwarten. Also bitte nochmal die Konsole im browser öffnen, die Instanz im edit-Modus ändern und die logs in der Konsole beobachten. 
Die Umschaltung der OID's findet durch Änderung des Instanz-Namens oder der Datenstruktur statt. Beides wird normalerweise wie oben geschrieben geloggt. Die Umschaltung selbst erfolgt, indem der Instanzname mit "weatherunderground" verglichen wird (wobei die Instanznummer keine Rolle spielt). Die Instanz laut log ist "weatherunderground.0", sollte also passen. Falls also hier Groß / Kleinschreibung ein Problem sein sollte? Als zweiter Schritt wird geprüft, ob es einen Datenpunkt "weatherunderground.0.forecast.0h.time". Den gibt es laut log, passt also auch. Also fehlt laut log nur der Trigger zur Umschaltung...

**Comment by oke24** [comment]
... der oben genannte Eintrag im Log kommt wie vor Dir erwartet, sobald ich "weatherunderground.0" als Wetterinstanz eintrage, wobei der Eintrag "instance changed to weatherunderground.0 old structure" 2x im Log erscheint, einmal mit "structure = NextDaysDetailed" und ein zweites Mal mit "structure = ". Nur die Umschaltung funktioniert leider noch nicht .... hier bleibt trotz Eintrag "weatherunderground.0" die Datenstruktur von DasWetter stehen ...
Anbei das Browser- Log vom Ziehen des Widgets in den Editor mit anschließendem Ändern der Wetterinstanz auf "weatherunderground.0".
Mit welchem Browser funktioniert es bei Dir ? Ich habe jetzt die aktuellen Versionen von Chromium (SR Iron Version 67.0.3500.0, Firefox 64.0, und IE) durchgetestet.

[vis-weather-2.2.1-1.log](https://github.com/rg-engineering/ioBroker.vis-weather/files/2717329/vis-weather-2.2.1-1.log)

**Comment by rg-engineering** [comment]
werden eigentlich die OID's gesetzt, oder sind die auch alle leer?

**Comment by oke24** [comment]
die OID's werden, sobald ich die Wetterinstanz auf "weatherunderground.0" setze, korrekt gesetzt

![vis-weather-2 2 1 -2](https://user-images.githubusercontent.com/46261409/50549737-f2b83e80-0c62-11e9-8d5a-1ff3f220242e.png)

**Comment by rg-engineering** [comment]
okay, dann habe ich den Fehler... Ich commite später noch ein update.

**Comment by rg-engineering** [comment]
V2.2.2 hier hochgeladen... Es war ein zusätzlicher check, der den user auf fehlende OID's aufmerksam machen sollte. Der funktioniert aber bei WU so leider nicht...
BTW: funktioniert WU noch? Bei mir kommen seit Wochen keine Daten mehr, und ich habe komplett auf DasWetter umgestellt. WU will ja den (kostenfreien) Dienst ja einstellen oder umstellen...

**Comment by oke24** [comment]
Vielen Dank für den schnellen Fix ! Der Chart wird jetzt wieder angezeigt. 
Was bei mir noch nicht funktioniert ist im Editor das Umschalten von "Datenstruktur" auf "Zeitintervall" bei der Wetterinstanz "weatherunderground.0".
Hier bleibt bei mir "Datenstruktur" mit den 3 Zeitperioden stehen. Die WU-Zeitintervalle von 1sec-24h werden bei mir nicht angezeigt (grüne Linien).

![vis-weather-2 2 1 -3](https://user-images.githubusercontent.com/46261409/50560613-e683be00-0d02-11e9-9777-eec537373ed8.png)
![vis-weather-2 2 1 -4](https://user-images.githubusercontent.com/46261409/50560614-eaafdb80-0d02-11e9-96d6-7d0b10f58ccd.png)
