### ISSUE TITLE
Feature Request: Hervorhebung Tage durch Farbwechsel

### ISSUE THREAD

**Issue by olderbag** [rg-engineering/ioBroker.vis-weather#13]
Zuerst mal: tolles Widget, leistet gute Dienste!

Ich hätte einen Vorschlag zur besseren Übersichtlichkeit. Am besten spricht hier ein Screenshot, den ich so zusammengebastelt habe:

![zwischenablage01](https://user-images.githubusercontent.com/39123738/51593925-93f98400-1ef3-11e9-8cee-d5ccb28442b6.jpg)

Also
- die Tage im Wechsel anders schattiert
- die Beschriftung mittig unter dem jeweiligen Zeitabschnitt

**Comment by rg-engineering** [comment]
@olderbag  Ich habe mal die erste Version für o.g. Änderung hochgeladen....
