### ISSUE TITLE
 color for the axis labeling is no longer considered

### ISSUE THREAD

**Issue by rg-engineering** [rg-engineering/ioBroker.vis-weather#22]
@Coffee-lover wrote:
Hi,
I don't know, if it is really the case, but it seems that since I've updated, the color for the axis labeling is no longer considered. This means I do not see them on dark views. Could you please check?
Thx.

**Comment by Hirsch-DE** [comment]
Hallo,
bei mir ist das selbe Problem. Es war schon in der Version vor dieser so. Egal was ich für Farben einstelle, es ist immer schwarze Schrift.
Gruß Thomas

**Comment by rg-engineering** [comment]
see my issue https://github.com/flot/flot/issues/1724

**Comment by rg-engineering** [comment]
@Hirsch-DE , @Coffee-lover könnt ihr die aktuelle Version hier mal ausprobieren?
Bei mir sieht das ganze jetzt so aus:

![grafik](https://user-images.githubusercontent.com/8238668/70082084-f4744a00-1609-11ea-8bec-6c69209f1ec3.png)

Die Farben sind aber jetzt auch einstellbar...

**Comment by Coffee-lover** [comment]
Das sieht gut aus. "Aktuelle Version" heißt Adapter über github aktualisieren?

**Comment by rg-engineering** [comment]
ja, bitte für den Test über github aktualisieren. Wenn okay, schiebe ich das ganze nach npm...

**Comment by Coffee-lover** [comment]
Ok, habe über das Handy aktualisiert. Vorläufig sehe ich das ganze Diagramm nicht. Muss ich später nochmal am Rechner checken.

**Comment by Coffee-lover** [comment]
Also - installierte Version 2.4.1.
Änderungen in der Eigenschaft "Farbe Achsbeschriftung" werden ignoriert.

`[{"tpl":"tplWeatherShowInstance","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":true,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","time_interval":"30 minutes","datastructure":"NextDaysDetailed","withxaxix":"true","axislabelcolor":"green","tickscolor":"#ffffff","withmarking":"true","markingcolor":"#eaebe5","xDateFormat":"%d.%b %H:%M","withborder":"true","nobgcolor":"true","withlegend":"false","legendposition":"ne","rainvisible":"true","rainchartType":"bar","raincolor":"#1d0ed8","chancerainvisible":"true","chanceraincolor":"#877efc","yRainVisible":"true","yChanceRainVisible":"true","tempvisible":"true","tempchartType":"line","tempcolor":"#00b3ac","maxY_temp":"0","minY_temp":"0","yTempVisible":"true","cloudschartType":"bar","sunorcloud":"sun","cloudcolor":"#f6ef3c","yCloudVisible":"true","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"instance":"daswetter.0","oid_date":"daswetter.0.NextDaysDetailed.Location_1.Day_1.day_value","oid_rain0":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1.rain_value","oid_chancerain0":"","oid_temp0":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1.temp_value","oid_cloud0":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1.clouds_value","oid_hour0":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1.hour_value","oid_rain1":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_2.rain_value","oid_chancerain1":"","oid_temp1":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_2.temp_value","oid_cloud1":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_2.clouds_value","oid_hour1":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_2.hour_value","oid_rain2":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_3.rain_value","oid_chancerain2":"","oid_temp2":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_3.temp_value","oid_cloud2":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_3.clouds_value","oid_hour2":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_3.hour_value","oid_rain3":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_4.rain_value","oid_chancerain3":"","oid_temp3":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_4.temp_value","oid_cloud3":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_4.clouds_value","oid_hour3":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_4.hour_value","oid_rain4":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_5.rain_value","oid_chancerain4":"","oid_temp4":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_5.temp_value","oid_cloud4":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_5.clouds_value","oid_hour4":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_5.hour_value","oid_rain5":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_6.rain_value","oid_chancerain5":"","oid_temp5":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_6.temp_value","oid_cloud5":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_6.clouds_value","oid_hour5":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_6.hour_value","oid_rain6":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_7.rain_value","oid_chancerain6":"","oid_temp6":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_7.temp_value","oid_cloud6":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_7.clouds_value","oid_hour6":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_7.hour_value","oid_rain7":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_8.rain_value","oid_chancerain7":"","oid_temp7":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_8.temp_value","oid_cloud7":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_8.clouds_value","oid_hour7":"daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_8.hour_value","oid_rain8":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_1.rain_value","oid_chancerain8":"","oid_temp8":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_1.temp_value","oid_cloud8":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_1.clouds_value","oid_hour8":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_1.hour_value","oid_rain9":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_2.rain_value","oid_chancerain9":"","oid_temp9":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_2.temp_value","oid_cloud9":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_2.clouds_value","oid_hour9":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_2.hour_value","oid_rain10":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_3.rain_value","oid_chancerain10":"","oid_temp10":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_3.temp_value","oid_cloud10":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_3.clouds_value","oid_hour10":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_3.hour_value","oid_rain11":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_4.rain_value","oid_chancerain11":"","oid_temp11":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_4.temp_value","oid_cloud11":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_4.clouds_value","oid_hour11":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_4.hour_value","oid_rain12":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_5.rain_value","oid_chancerain12":"","oid_temp12":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_5.temp_value","oid_cloud12":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_5.clouds_value","oid_hour12":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_5.hour_value","oid_rain13":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_6.rain_value","oid_chancerain13":"","oid_temp13":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_6.temp_value","oid_cloud13":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_6.clouds_value","oid_hour13":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_6.hour_value","oid_rain14":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_7.rain_value","oid_chancerain14":"","oid_temp14":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_7.temp_value","oid_cloud14":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_7.clouds_value","oid_hour14":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_7.hour_value","oid_rain15":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_8.rain_value","oid_chancerain15":"","oid_temp15":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_8.temp_value","oid_cloud15":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_8.clouds_value","oid_hour15":"daswetter.0.NextDaysDetailed.Location_1.Day_2.Hour_8.hour_value","oid_rain16":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_1.rain_value","oid_chancerain16":"","oid_temp16":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_1.temp_value","oid_cloud16":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_1.clouds_value","oid_hour16":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_1.hour_value","oid_rain17":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_2.rain_value","oid_chancerain17":"","oid_temp17":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_2.temp_value","oid_cloud17":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_2.clouds_value","oid_hour17":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_2.hour_value","oid_rain18":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_3.rain_value","oid_chancerain18":"","oid_temp18":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_3.temp_value","oid_cloud18":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_3.clouds_value","oid_hour18":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_3.hour_value","oid_rain19":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_4.rain_value","oid_chancerain19":"","oid_temp19":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_4.temp_value","oid_cloud19":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_4.clouds_value","oid_hour19":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_4.hour_value","oid_rain20":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_5.rain_value","oid_chancerain20":"","oid_temp20":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_5.temp_value","oid_cloud20":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_5.clouds_value","oid_hour20":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_5.hour_value","oid_rain21":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_6.rain_value","oid_chancerain21":"","oid_temp21":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_6.temp_value","oid_cloud21":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_6.clouds_value","oid_hour21":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_6.hour_value","oid_rain22":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_7.rain_value","oid_chancerain22":"","oid_temp22":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_7.temp_value","oid_cloud22":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_7.clouds_value","oid_hour22":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_7.hour_value","oid_rain23":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_8.rain_value","oid_chancerain23":"","oid_temp23":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_8.temp_value","oid_cloud23":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_8.clouds_value","oid_hour23":"daswetter.0.NextDaysDetailed.Location_1.Day_3.Hour_8.hour_value","oid_rain24":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_1.rain_value","oid_chancerain24":"","oid_temp24":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_1.temp_value","oid_cloud24":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_1.clouds_value","oid_hour24":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_1.hour_value","oid_rain25":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_2.rain_value","oid_chancerain25":"","oid_temp25":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_2.temp_value","oid_cloud25":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_2.clouds_value","oid_hour25":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_2.hour_value","oid_rain26":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_3.rain_value","oid_chancerain26":"","oid_temp26":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_3.temp_value","oid_cloud26":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_3.clouds_value","oid_hour26":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_3.hour_value","oid_rain27":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_4.rain_value","oid_chancerain27":"","oid_temp27":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_4.temp_value","oid_cloud27":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_4.clouds_value","oid_hour27":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_4.hour_value","oid_rain28":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_5.rain_value","oid_chancerain28":"","oid_temp28":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_5.temp_value","oid_cloud28":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_5.clouds_value","oid_hour28":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_5.hour_value","oid_rain29":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_6.rain_value","oid_chancerain29":"","oid_temp29":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_6.temp_value","oid_cloud29":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_6.clouds_value","oid_hour29":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_6.hour_value","oid_rain30":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_7.rain_value","oid_chancerain30":"","oid_temp30":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_7.temp_value","oid_cloud30":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_7.clouds_value","oid_hour30":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_7.hour_value","oid_rain31":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_8.rain_value","oid_chancerain31":"","oid_temp31":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_8.temp_value","oid_cloud31":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_8.clouds_value","oid_hour31":"daswetter.0.NextDaysDetailed.Location_1.Day_4.Hour_8.hour_value","oid_rain32":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_1.rain_value","oid_chancerain32":"","oid_temp32":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_1.temp_value","oid_cloud32":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_1.clouds_value","oid_hour32":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_1.hour_value","oid_rain33":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_2.rain_value","oid_chancerain33":"","oid_temp33":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_2.temp_value","oid_cloud33":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_2.clouds_value","oid_hour33":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_2.hour_value","oid_rain34":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_3.rain_value","oid_chancerain34":"","oid_temp34":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_3.temp_value","oid_cloud34":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_3.clouds_value","oid_hour34":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_3.hour_value","oid_rain35":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_4.rain_value","oid_chancerain35":"","oid_temp35":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_4.temp_value","oid_cloud35":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_4.clouds_value","oid_hour35":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_4.hour_value","oid_rain36":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_5.rain_value","oid_chancerain36":"","oid_temp36":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_5.temp_value","oid_cloud36":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_5.clouds_value","oid_hour36":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_5.hour_value","oid_rain37":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_6.rain_value","oid_chancerain37":"","oid_temp37":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_6.temp_value","oid_cloud37":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_6.clouds_value","oid_hour37":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_6.hour_value","oid_rain38":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_7.rain_value","oid_chancerain38":"","oid_temp38":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_7.temp_value","oid_cloud38":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_7.clouds_value","oid_hour38":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_7.hour_value","oid_rain39":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_8.rain_value","oid_chancerain39":"","oid_temp39":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_8.temp_value","oid_cloud39":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_8.clouds_value","oid_hour39":"daswetter.0.NextDaysDetailed.Location_1.Day_5.Hour_8.hour_value","cloudsvisible":true},"style":{"left":"255px","top":"526px","width":"500px","color":"green"},"widgetSet":"weather"}]`

**Comment by rg-engineering** [comment]
Bei mir sieht dein widget nach import dann so aus:

![grafik](https://user-images.githubusercontent.com/8238668/70149260-04db0200-16a8-11ea-9ad9-a8d1af8ac72d.png)

Hast du die Eisntellungen "Farbe Achse" und "Farbe Tick Label" bei dir auch? Falls nicht, bitte noch ein upload Visualisierung durchführen.

![grafik](https://user-images.githubusercontent.com/8238668/70149392-466bad00-16a8-11ea-95d1-72240d6b3c65.png)

**Comment by Coffee-lover** [comment]
Hey. Ich musste meinen JS.Controller updaten. Jetzt sind die Eingabemöglichkeiten da. Damit sind die Beschriftungen wieder lesbar.
Es gibt noch einen Schönheitsfehler: Die Schriftart, die unter fonts eingestellt ist, wird bei den Beschriftungen nicht angezogen.
Dennoch schon einmal danke für das Update.

**Comment by Coffee-lover** [comment]
Außerdem fällt auf, dass der 5. Balken etwas schmäler als die anderen 4 ist. Gehört das hier rein, oder hast du dafür lieber ein eigenes Issue?

**Comment by rg-engineering** [comment]
Die Schrift unter CSS/fonts kann ich nicht direkt verwenden. Stattdessen habe ich jetzt in den Haupteinstellungen die Schriftart hinzugefügt...siehe auch #20 

Der Sprung bzgl. der Spaltenbreite liegt anscheinend an den Daten, die von DasWetter kommen. Die wechseln anscheinend die Zeitabstände zwischen den einzelnen Datenpunkten.
Bei mir sieht das so aus:

![grafik](https://user-images.githubusercontent.com/8238668/70338198-c29ef580-184c-11ea-8353-a4061a8a5273.png)

Genau hier wechselt der Abstand der Datenpunkte einmalig von 3 Stunden auf 2 Stunden und bleibt dann wieder 3 Stunden. Habe noch keine Idee, wie ich das korrigiere...

**Comment by Coffee-lover** [comment]
Danke für die Info zur Schriftart.

Mit dem Schönheitsfehler mit den Punkten muss ich wohl leben, da sich die dynamisch mit dem Zeitpunkt ändern. Ein Workaround wäre in meinen Augen nur möglich, indem man sich die Datenpunkte per Script einfriert. Mal überlegen, ob ich mir die Mühe dazu machen möchte.

Danke für deinen Einsatz. 👍

**Comment by Coffee-lover** [comment]
Hi @rg-engineering 
trotz Updates und Upload bekomme ich die Anzeige zum Einstellen der Schriftart nicht. Bei mir wird schlicht nichts angezeigt. Habe ich beim Adapter Update etwas falsch gemacht oder hast du noch eine andere Idee?
VG

**Comment by rg-engineering** [comment]
wie installierst du? direkt über github? Mittlerweile liegt die Version als 3.5.2 im npm und damit im latest repository von iobroker und wird somit als "verfügbar" angezeigt, so dass man direkt aus iobroker updaten kann. Das sollte auf jeden Fall funktionieren. wird dir im iobroker diese Version auch als installiert angezeigt? Ich hatte manchmal das Problem, dass die vis-Adapter irgendwo im cache liegen und neue nicht verwendet werden. Im worst case musste ich das System, auf dem vis läuft, neu starten...

**Comment by Coffee-lover** [comment]
Ja, hatte direkt über Github installiert. Er zeigt mir als installiert die *2*.5.2 an. Mal sehen, dass ich die 3 drauf bringe und das System neu starte.
Danke.
