### ISSUE TITLE
Legende zeigt clouds statt sun

### ISSUE THREAD

**Issue by Hirsch-DE** [rg-engineering/ioBroker.vis-weather#23]
Hallo,
bei Wolken habe ich Sonne statt Wolken eingestellt. In der Legende steht aber clouds.
Gibt es dazu auch die Übersetzung in andere Sprachen (Deutsch) für die Legende?
Gruß Thomas

**Comment by rg-engineering** [comment]
Das baue ich ein...

**Comment by rg-engineering** [comment]
Die Eisntellung ist nun vorhanden...
