### ISSUE TITLE
no OIDs specified

### ISSUE THREAD

**Issue by loemic87** [rg-engineering/ioBroker.vis-weather#31]
After generating API-Links on daswetter.com the widget gets the following error:

"no OID's for DasWetter specified"

I used the 2nd link on daswetter.com and pasted the link in 2nd line in the instance.

Did i do anything wrong?

**Comment by rg-engineering** [comment]
when you add the name of your instance, then oid's should be created automatically:

![grafik](https://user-images.githubusercontent.com/8238668/113419818-8344d280-93c8-11eb-90b0-ab014873c49e.png)


![grafik](https://user-images.githubusercontent.com/8238668/113419838-8e97fe00-93c8-11eb-8bd9-7199770d42f7.png)

If you still have a problem be more specific in error description...
