### ISSUE TITLE
Please update the Adapter for the new data structure from weatherunderground and daswetter

### ISSUE THREAD

**Issue by ewertmaster** [rg-engineering/ioBroker.vis-weather#9]

**Comment by rg-engineering** [comment]
with latest commits here I added support for new data structure already. I will release it in NPM very soon.

**Comment by ewertmaster** [comment]
The issue comes out after I update the weatherunderground Adapter to Version 2.0.3. I also tried daswetter but without success. I already use the vis-weather version 2.0.0.

**Comment by ewertmaster** [comment]
I have tried the version 2.1.0. This does not work for me with WU yet. It seems that the times are not interpreted correctly.

**Comment by rg-engineering** [comment]
probably. time string is one of the changes in WU 2.x ...
can you please post how your time string looks like?

**Comment by ewertmaster** [comment]
This is what the chart looks like:
<img width="568" alt="bildschirmfoto 2018-08-22 um 00 23 10" src="https://user-images.githubusercontent.com/42463785/44432547-c4cf3900-a5a2-11e8-8277-8833e0ad955a.png">

**Comment by ewertmaster** [comment]
<img width="1556" alt="bildschirmfoto 2018-08-22 um 00 34 43" src="https://user-images.githubusercontent.com/42463785/44432683-5b035f00-a5a3-11e8-9fe6-63aa9abd3a7f.png">

**Comment by ewertmaster** [comment]
I found out by chance today that when I add the widget with firefox it works. So far I have used Safari Browser.

**Comment by rg-engineering** [comment]
and I always test with firefox and chrome... I'll check that...

**Comment by rg-engineering** [comment]
for me everything looks good and fine... Your time string is the same as on my test system, so I guess the problem is somewhere else. Can you please post a browser log like issue #11 ? Would be great to get an idea where to look for the problem. Please take latest version here (I added some more logs).

**Comment by rg-engineering** [comment]
@ewertmaster is this issue closed now?
