### ISSUE TITLE
Please state compatibility with vis-2

### ISSUE THREAD

**Issue by mcm1957** [rg-engineering/ioBroker.vis-weather#97]
Please add a note to README:md stating wether this vis adapter

- is compatible with vis-2 / next generation vis
- is not yet checked for compatibility with vis-2
- is NOT compatile with vis-2 and
  - will be adapted in the near futere
  - will not be adapted
  - will be replaced by an oterh adapter for vis-2

Thanks

**Comment by rg-engineering** [comment]
just checking compatibility, but it doesn't seem to be the case.

**Comment by rg-engineering** [comment]
This widget is NOT compatible with vis-2.
A new version under the name vis-2-weather is under preparation.
Same statement added in readme
